### ISSUE TITLE
please link proper repo / remove this one

### ISSUE THREAD

**Issue by axe312ger** [semantic-release/last-release-git-tag#2]
hey there, i was looking for this module and ended up in this empty repo. Can you please link to this right one? https://github.com/finom/last-release-git

**Comment by axe312ger** [comment]
I just realised that @finom's repo is very fresh. Maybe consider merge or owner transfer? :)

**Comment by cyberhck** [comment]
Please delete this repo and use finom's repo, I was about to write a plugin myself.
